"""Streamlit UI for the Phase 3 Human-in-the-Loop pilot."""

from __future__ import annotations

from datetime import datetime, timezone
import os
from pathlib import Path

import streamlit as st

from src.cybermatch.pilot.service import PilotEvaluationService
from src.cybermatch.pilot.environment import load_pilot_environment


ROOT = Path(__file__).resolve().parents[1]
load_pilot_environment(ROOT)
service = PilotEvaluationService(
    ROOT,
    llm_config_path=os.environ.get("CYBERMATCH_PILOT_LLM_CONFIG"),
)
st.set_page_config(page_title="CyberMatch Pilot", layout="wide")
st.title("CyberMatch Human-in-the-Loop Pilot")
st.warning("The LLM assists with explanation. CyberMatch computes metrics; a human approves and decides.")
runtime = service.gateway_status()
if runtime["mode"] == "ai-assisted":
    st.info(
        f"AI explanation enabled by operational configuration: "
        f"{runtime['provider_id']} / {runtime['model_id']}"
    )
else:
    st.info("Offline deterministic explanation is active; no Result View is sent externally.")

with st.form("pilot"):
    question = st.text_area("What decision do you want to make?", max_chars=500)
    run_id = st.text_input("Run ID", value="pilot-001-run-001")
    approver = st.text_input("Approver")
    approved = st.checkbox("I approve the displayed replay, protocol, evidence class, and execution")
    st.json(service.catalog_view())
    submitted = st.form_submit_button("Run approved evaluation")

if submitted:
    spec = {
        "schema_version": "1.0",
        "run_id": run_id,
        "decision_question": question,
        "evaluation_type": "external_replay",
        "scenario_id": "agentic-boundary-pressure-external",
        "evidence_class": "replay-backed",
        "source_id": "ocsf-boundary-escape-fixture-v1",
        "mapping_id": "ocsf_security_finding_v1",
        "recipe_id": "agentic_boundary_pressure_v1",
        "seed": 0,
        "human_approval": {
            "status": "approved" if approved else "draft",
            "approved_by": approver,
            "approved_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        },
    }
    try:
        result = service.execute(spec)
    except (OSError, ValueError, RuntimeError) as exc:
        st.error(str(exc))
    else:
        st.session_state["pilot_result"] = result

result = st.session_state.get("pilot_result")
if result:
    view = result["result_view"]
    explanation = result["explanation"]
    answer = explanation["answer"]
    audit = explanation["audit"]

    st.divider()
    st.header("Measured CyberMatch result")
    st.caption("Deterministic evaluator output; not generated by the AI provider.")
    st.success(f"Verified {view['evidence_class']} result — bundle {view['bundle_hash']}")
    metric_col, status_col, evidence_col = st.columns(3)
    metric_col.metric("F1", view["metrics"]["f1"])
    status_col.metric("Run status", view["status"])
    evidence_col.metric("Evidence class", view["evidence_class"])

    st.divider()
    st.header("AI-assisted explanation")
    st.caption("Advisory explanation only; the measured result above remains authoritative.")
    if audit["validation_status"] == "accepted":
        st.info(
            f"AI answer accepted: {audit['provider_id']} / {audit['resolved_model']}"
        )
    elif audit["failure_class"]:
        st.warning(
            "AI answer was unavailable or rejected; a deterministic template is shown. "
            f"Failure class: {audit['failure_class']}"
        )
    else:
        st.info("Deterministic template explanation is active.")
    st.write(answer["conclusion"])
    st.dataframe(answer["claims"], use_container_width=True)
    st.warning("\n".join(answer["limitations"]))
    with st.expander("Non-content LLM audit"):
        st.json(audit)

    st.divider()
    st.header("Human decision")
    with st.form("human-decision"):
        decision = st.selectbox(
            "Decision", ["additional_validation", "accept", "reject"]
        )
        rationale = st.text_area("Decision rationale", max_chars=2000)
        decided_by = st.text_input("Decision maker")
        decision_submitted = st.form_submit_button("Record final human decision")
    if decision_submitted:
        try:
            decision_path = service.record_decision(
                str(view["run_id"]),
                decision=decision,
                rationale=rationale,
                decided_by=decided_by,
            )
        except (OSError, ValueError, RuntimeError) as exc:
            st.error(str(exc))
        else:
            st.success(f"Human decision recorded: {decision_path}")
