"""Static labels and bilingual (Japanese / English) UI text for the Streamlit dashboard."""

PROFILE_COLUMNS = [
    "name",
    "category",
    "detection_boost",
    "interruption_boost",
    "diversion_boost",
    "confidence_boost",
    "false_positive_penalty",
    "latency_penalty",
    "maintenance_penalty",
]

MISSION_OPTIONS = ["profit", "achievement", "persistence", "critical_hunter"]
MISSION_LABELS = {
    "profit": "金銭獲得",
    "achievement": "目標達成",
    "persistence": "継続的な潜伏",
    "critical_hunter": "重要資産の探索",
}
PRODUCT_CATEGORY_LABELS = {
    "ids": "IDS（侵入検知）",
    "ips": "IPS（侵入防御）",
    "honeypot": "ハニーポット",
    "deception": "デセプション",
    "xdr": "XDR（統合検知・対応）",
}
TOPOLOGY_LABELS = {
    "cloud_native": "クラウドネイティブ企業",
    "enterprise": "一般的な企業ネットワーク",
    "hospital_network": "病院ネットワーク",
    "ot_environment": "OT・工場環境",
    "small_business": "小規模事業者環境",
}
TOPOLOGY_DESCRIPTIONS = {
    "cloud_native": "ID基盤への依存が高く、資産構成が変化しやすいクラウド中心の環境です。",
    "enterprise": "集中したID基盤と複数の業務資産を持つ、一般的な企業環境です。",
    "hospital_network": "業務停止への影響が大きく、医療関連の重要資産を持つ環境です。",
    "ot_environment": "工場設備などの重要資産が集中し、業務停止への影響が高い環境です。",
    "small_business": "重要資産と構成の複雑さが比較的小さい事業者環境です。",
}
SCENARIO_LABELS = {
    "financial_enterprise": "金融企業",
    "hospital_enterprise": "病院・医療機関",
    "cloud_native_startup": "クラウドネイティブ企業",
    "ot_factory": "OT・工場",
    "small_business": "小規模事業者",
}
SCENARIO_DESCRIPTIONS = {
    "financial_enterprise": "ID基盤への依存と業務停止への敏感さが高い金融企業を想定します。",
    "hospital_enterprise": "医療業務への影響が大きく、運用停止を避ける必要がある病院を想定します。",
    "cloud_native_startup": "ID基盤への依存とデコイの活用余地が高いクラウド中心の企業を想定します。",
    "ot_factory": "重要な制御設備があり、業務停止への影響が高い工場を想定します。",
    "small_business": "資産数と構成の複雑さが比較的小さい事業者を想定します。",
}
JAPANESE_REPORT_INFO = {
    "PHASE90_INTENT_INFERENCE_REPORT.md": ("攻撃者の目的を推定する分析レポート", "観測された攻撃者行動から、設定した攻撃者の目的をどの程度推定できたかを確認します。"),
    "PHASE91_BEHAVIOR_PROFILE_REPORT.md": ("攻撃者行動の傾向分析レポート", "攻撃者の行動を傾向別に分類し、攻撃者の目的との関係を確認します。"),
    "PHASE92_FEATURE_SPACE_REPORT.md": ("評価特徴量の分析レポート", "どの特徴が分析結果に強く影響しているかを確認します。"),
    "PHASE93_PROFILECORE_REPORT.md": ("行動プロファイル統合分析レポート", "攻撃者行動の特徴から、行動タイプの候補を確認します。"),
    "PHASE94_ARCHETYPE_INTERPRETATION_REPORT.md": ("攻撃者タイプの解釈レポート", "抽出された攻撃者タイプの特徴と、目的・行動傾向との関係を確認します。"),
    "PHASE95_STRATEGY_LAYER_REPORT.md": ("攻撃戦略の分析レポート", "攻撃者の目的と行動の間にある攻撃戦略の傾向を確認します。"),
    "PHASE96_TAXONOMY_REPORT.md": ("攻撃者目的・対象の関係分析レポート", "攻撃の意図、目的、対象、戦略の関係を確認します。"),
    "PHASE97_TARGET_STRATEGY_REPORT.md": ("対象別の攻撃戦略分析レポート", "攻撃対象によって、どの攻撃戦略が選ばれやすいかを確認します。"),
    "PHASE98_STRATEGY_VALIDATION_REPORT.md": ("攻撃戦略モデルの検証レポート", "攻撃対象と戦略の関係モデルが、既存データとどの程度整合するかを確認します。"),
    "PHASE99_DECISION_GRAPH_REPORT.md": ("攻撃者の意思決定経路レポート", "攻撃の意図から行動傾向までの意思決定経路を確認します。"),
}
JAPANESE_REPORT_SECTIONS = {
    "Summary": "結果の要約",
    "Method": "分析の前提",
    "Confusion Matrix": "推定結果の対応表",
    "Rows": "分析対象の詳細",
    "Profile Distribution": "行動傾向の分布",
    "Mission Relationship": "攻撃者目的との関係",
    "Dominant Feature Ranking": "影響の大きい特徴",
    "Archetype Candidates": "攻撃者タイプ候補",
    "Principal Components": "主な分析軸",
    "Archetype Summary": "攻撃者タイプの要約",
    "Feature Distance": "タイプ間の特徴差",
    "Mission Distribution": "攻撃者目的の分布",
    "Strategy Distribution": "攻撃戦略の分布",
    "Future Integration": "今後の拡張",
    "Intents": "攻撃の意図",
    "Missions": "攻撃者の目的",
    "Targets": "攻撃対象",
    "Taxonomy Edges": "意図・目的・対象・戦略の関係",
    "Target Strategy Mapping": "対象と攻撃戦略の対応",
    "Observed Rows": "観測結果の詳細",
    "Validation Metrics": "検証指標",
    "Strategy Summary": "攻撃戦略の要約",
    "Graph Structure": "意思決定経路の構造",
    "Metrics": "指標",
    "Node Explorer": "構成要素",
}
JAPANESE_REPORT_TERMS = {
    "critical_hunter": "重要資産の探索",
    "persistence": "継続的な潜伏",
    "achievement": "目標達成",
    "profit": "金銭獲得",
    "financial_gain": "金銭獲得",
    "long_term_presence": "長期潜伏",
    "credential_theft": "認証情報の窃取",
    "data_exfiltration": "情報の持ち出し",
    "service_disruption": "サービス妨害",
    "infrastructure_takeover": "基盤の乗っ取り",
    "long_term_persistence": "長期的な潜伏",
    "supply_chain_compromise": "サプライチェーン侵害",
    "identity_infrastructure": "ID基盤",
    "critical_database": "重要データベース",
    "business_application": "業務アプリケーション",
    "cloud_control_plane": "クラウド管理基盤",
    "backup_system": "バックアップシステム",
    "research_system": "研究システム",
    "industrial_control_system": "産業制御システム",
    "trust_relationship": "信頼関係",
    "critical_asset_hunter": "重要資産探索型",
    "credential_hunter": "認証情報探索型",
    "persistence_builder": "潜伏基盤構築型",
    "process_manipulator": "プロセス操作型",
    "research_explorer": "研究資産探索型",
    "secret_hunter": "機密情報探索型",
    "trust_abuser": "信頼関係悪用型",
    "resource_exhaustion": "リソース枯渇型",
    "utility_seeking": "効用重視型",
    "stealth_seeking": "隠密行動重視型",
    "disruption_seeking": "妨害重視型",
    "critical_path_seeking": "重要資産経路重視型",
    "opportunistic": "機会追随型",
    "Mission inference accuracy": "目的推定の一致率",
    "Mean mission confidence": "目的推定の平均確信度",
    "Mean mission entropy": "目的推定の曖昧さ",
    "Profile differences observed": "行動傾向の違いが観測されたか",
    "Profiles observed": "観測された行動傾向数",
    "Profile concentration": "行動傾向の集中度",
    "Mean profile confidence": "行動傾向推定の平均確信度",
    "Dominant feature": "最も影響が大きい特徴",
    "normalized weight": "正規化した重み",
    "strategy": "攻撃戦略",
    "mission": "攻撃者目的",
    "target": "攻撃対象",
    "confidence": "確信度",
    "accuracy": "一致率",
    "true": "設定値",
    "inferred": "推定値",
    "feature": "特徴",
    "profile": "行動傾向",
    "archetype": "攻撃者タイプ",
    "intent": "攻撃の意図",
    "rows": "件数",
    "count": "件数",
    "value": "値",
    "metric": "評価項目",
}

TEXT = {
    "日本語": {
        "nav": ["ホーム", "シナリオ", "製品", "実行", "結果", "ベンチマーク", "脅威ハンティング"],
        "nav_to_key": {
            "ホーム": "home",
            "シナリオ": "scenario",
            "製品": "products",
            "実行": "run",
            "結果": "results",
            "ベンチマーク": "benchmark",
            "脅威ハンティング": "hunting",
        },
        "language": "表示言語",
        "report_locale": "ja",
        "scope": "防御策の比較評価",
        "home_subtitle": "防御策比較ダッシュボード",
        "definition": (
            "CyberMatch は、システムを狙う攻撃者の思考や行動をシミュレーションし、"
            "どのセキュリティ対策（防御戦略や製品）が最も効果的かを比較・評価できるツールです。"
        ),
        "mvp_scope": (
            "このダッシュボードでは、「想定される環境」と「攻撃者の狙い」に対して、"
            "複数のセキュリティ対策を簡単に比較・評価できます。"
        ),
        "cert_warning": (
            "※ 本ツールは「どの環境でも最強の製品」を保証するものではありません。"
            "攻撃者の目的に応じて対策の効果がどう変わるかを比較・分析するための参考情報としてご利用ください。"
        ),
        "current_focus": """
        **このツールの主な機能**

        - 「どんな環境で」「どんな目的の攻撃者に」「どの対策を使うか」を選択
        - 選んだ対策の効果を比較し、「なぜその対策が効くのか」という理由を確認
        - 実行したシミュレーション条件と結果のレポートを保存
        """,
        "home_how_to": """
        **使い方（3ステップで簡単にはじめられます）**

        1. **実行** ページを開き、**デモシナリオ**から試したい業種や環境を選びます。
        2. **このデモ条件を適用** ボタンを押すと、攻撃者の目的や防御策が自動でセットされます。
        3. **防御策の比較を実行** ボタンを押し、完了したら **結果** ページでどの対策が最も有効だったかを確認します。

        CyberMatchを使えば、「自社の環境や想定される攻撃に対して、どのセキュリティ製品から検討すべきか」の当たりをつけることができます。
        """,
        "scenario_title": "シナリオ",
        "scenario_import": "評価条件ファイルを確認",
        "scenario_catalog": "業種別の想定シナリオ",
        "demo_scenarios": "デモシナリオ",
        "apply_demo": "このデモ条件を適用",
        "demo_conclusion": "デモで伝える結論",
        "demo_applied": "適用中のデモ",
        "no_demo_scenarios": "scenarios/demos/ 配下にデモシナリオが見つかりません。",
        "scenario_name": "シナリオ名",
        "scenario_industry": "想定業種",
        "scenario_description": "このシナリオで想定する状況",
        "scenario_page_guide": "「シナリオ」とは、どのような組織（業種）や攻撃目的を想定して対策を比較するかを決める設定のことです。JSONファイルは、評価の前提条件を記録した単なる設定ファイルです。",
        "scenario_catalog_guide": "業種ごとの代表的なシナリオ一覧です。金融、病院、クラウド企業、工場など、よくある前提条件を確認できます。実際にシミュレーションを回す際の条件は「実行」ページで設定します。",
        "scenario_file_guide": "評価条件ファイルには、想定環境・攻撃者の目的・比較する対策などの情報が保存されています。通常は変更する必要はありませんが、詳細を確認したい場合のみ開いてください。",
        "json_detail": "設定ファイルの詳細（JSON）",
        "benchmark_suite": "全体傾向の確認（ベンチマーク）",
        "benchmark_guide": "「ベンチマーク」は、複数のシナリオや環境をまとめてシミュレーションし、防御策の全体的な傾向をつかむための機能です。特定の案件の結論というより、広い視点での傾向分析に役立ちます。",
        "benchmark_name": "ベンチマーク名",
        "scenario_count": "シナリオ数",
        "mission_count": "攻撃者目的数",
        "product_count": "比較する防御策数",
        "topology_count": "想定環境数",
        "matrix_size": "比較パターン数",
        "benchmark_json": "ベンチマーク設定ファイル",
        "no_benchmarks": "benchmarks/ 配下にベンチマーク設定ファイルが見つかりません。",
        "topology_library": "想定ネットワーク（Topology）",
        "topology_guide": "「想定環境」は、守るべき重要資産の数やネットワークの構造、業務停止による影響の大きさなどをモデル化したものです。実際の複雑なネットワーク構成をそのまま読み込むものではありません。",
        "topology_name": "想定環境名",
        "topology_description": "想定環境の説明",
        "topology_characteristics": "比較に使う環境特性",
        "topology_json": "想定環境の設定ファイル",
        "no_topologies": "topologies/ 配下に想定環境の設定ファイルが見つかりません。",
        "scenario_json": "評価条件ファイル",
        "selected_scenario_path": "選択中の設定ファイル",
        "no_scenarios": "scenarios/ 配下に評価条件ファイルが見つかりません。",
        "scenario_selector": "評価の種類",
        "mission_selection": "攻撃者の目的",
        "mission_caption": "チェックを入れた攻撃目的について、それぞれの防御策がどれだけ効くかをシミュレーションします。複数選ぶと「目的ごとにどの対策が向いているか」を比較できます。",
        "products_title": "比較する防御策",
        "no_profiles": "profiles/products/ 配下に防御策の設定ファイルが見つかりません。",
        "comparison_targets": "比較する防御策",
        "product_caption": "比較したい対策にチェックを入れてください。※これらは特定の製品そのものではなく、「IDS」「IPS」「XDR」といった一般的な製品特性をモデル化したものです。",
        "run_title": "実行",
        "run_guide": "初心者の方は、まず **デモシナリオ** から「このデモ条件を適用」ボタンを押して条件を自動セットすることをおすすめします。手動で設定する場合は、想定環境、攻撃者の目的、比較する防御策をそれぞれ選んでください。",
        "scenario_import_hook": "評価条件ファイルを選ぶ",
        "primary_runner": "実行する評価:",
        "output": "出力先:",
        "run_phase63": "防御策の比較を実行",
        "run_phase83": "横断ベンチマーク比較を実行",
        "run_standard_benchmark": "標準条件で横断比較を実行",
        "stop_run": "実行を停止",
        "running_phase63": "防御策の比較を実行中...",
        "runner_failed": "Runner が失敗しました",
        "runner_running": "Evaluation is running.",
        "runner_stopped": "Evaluation を停止しました。",
        "runner_exit_code": "終了コード",
        "runner_not_running": "実行中のrunnerはありません。",
        "phase63_done": "防御策の比較が完了しました。",
        "phase83_done": "横断ベンチマーク比較が完了しました。",
        "phase85_done": "標準条件での横断比較が完了しました。",
        "phase62_done": "防御策プロファイルの基礎比較が完了しました。",
        "artifacts_written": "結果の保存先:",
        "optional_phase62": "防御策プロファイルの基礎比較（詳細）",
        "run_phase62": "防御策プロファイルの基礎比較を実行",
        "running_phase62": "防御策プロファイルの基礎比較を実行中...",
        "results_title": "結果",
        "decision_conclusion": "結論",
        "decision_conclusion_intro": "選択した条件での推奨候補と、攻撃者の目的別の最適候補です。",
        "decision_reason": "理由",
        "decision_reason_intro": "各攻撃者目的の推奨候補について、最も大きく変化した攻撃者行動を示します。",
        "decision_primary_driver": "主な変化",
        "decision_driver_success": "攻撃者目的の達成率低下",
        "decision_driver_disruption": "攻撃活動の妨害増加",
        "decision_driver_detection": "検知確率の増加",
        "decision_driver_diversion": "攻撃者の迂回・無駄行動の増加",
        "decision_comparison": "比較",
        "decision_comparison_intro": "防御策と攻撃者目的の組合せごとの効果差を比較します。数値は選択した前提条件におけるモデル評価です。",
        "decision_constraints": "前提・制約",
        "decision_constraints_text": "本結果は、設定した条件に基づくシミュレーション上の比較評価であり、実際の環境での効果を完全に保証するものではありません。",
        "advanced_analysis": "分析詳細",
        "run_summary_title": "今回の評価のまとめ",
        "run_summary_intro": "選択した条件でのシミュレーション結果です。まずはこの概要から確認してください。",
        "summary_environment": "想定環境",
        "summary_missions": "攻撃者の目的",
        "summary_products": "比較した防御策",
        "summary_result": "主な結果",
        "summary_seed": "再現用seed",
        "summary_recommendation": "今回の条件では、総合的に見て「 `{product}` 」が最も高い効果を示しました。ただし、攻撃の目的によっては別の対策が最適な場合もあります。",
        "run_conditions": "実行条件の詳細",
        "run_manifest": "実行条件（JSON）",
        "select_topology_error": "評価前に想定環境を1つ選択してください。",
        "select_mission_error": "評価前に攻撃者の目的を1つ以上選択してください。",
        "select_product_error": "評価前に比較する防御策を1つ以上選択してください。",
        "results_missing": "結果が見つかりません。先に「実行」ページで比較を実行してください。",
        "go_to_run": "実行ページで「防御策の比較を実行」を押してください。",
        "expected_output_path": "結果の保存先",
        "missing_files": "不足している結果ファイル",
        "results_intro": (
            "この画面では、シミュレーション結果（どの防御策が一番効果的だったか）を確認できます。"
            "表示される数値は実環境での確実な効果を保証するものではなく、設定した条件に基づく比較・参考値です。"
        ),
        "interpretation_notice": (
            "CyberMatchは「どの環境でも最強の製品」を決めるものではありません。"
            "攻撃者が何を狙っているか（目的）によって、防御策の効果がどう変わるかを比較・分析するためのツールです。"
        ),
        "summary_cards": "比較結果の要点",
        "best_product_overall": "総合的に高い候補",
        "best_product_per_mission": "目的別の有力候補数",
        "worst_mission_coverage": "平均効果が低い目的",
        "highest_mission_variance": "目的による差が大きい候補",
        "single_winner_exists": "全目的で同じ候補か",
        "product_mission_table": "防御策と攻撃者目的の比較表",
        "product_mission_chart": "防御策と攻撃者目的の比較ヒートマップ",
        "winner_explanation": "目的別の有力候補の説明",
        "product_detail": "選択した防御策の詳細",
        "product_selector": "確認する防御策",
        "detail_metric": "評価項目",
        "detail_value": "値",
        "per_mission_detail": "目的ごとの詳細",
        "summary_table": "全比較結果（詳細）",
        "heatmap": "防御策と攻撃者目的のヒートマップ",
        "heatmap_help": "縦軸は比較する防御策、横軸は攻撃者の目的です。色が濃いほど、その組合せで防御策の比較スコアが高いことを示します。",
        "variance": "攻撃者の目的による効果のばらつき",
        "variance_help": "同じ防御策でも、攻撃者の目的によって効果がどの程度変わるかを表します。値が大きいほど、目的による効果差が大きいことを示します。",
        "phase62_comparison": "基礎比較と目的別比較の違い",
        "phase62_help": "防御策そのものの基礎比較と、攻撃者の目的を考慮した比較の違いを示します。目的別比較では、単一の順位ではなく、どの目的に適するかを確認します。",
        "markdown_report": "評価レポート（Markdown）",
        "json_summary": "結果データ（JSON）",
        "downloads": "結果ファイルをダウンロード",
        "benchmark_artifacts": "横断ベンチマーク比較の結果",
        "phase90_intent_inference": "攻撃者の目的を推定する分析（研究用）",
        "phase90_missing": "攻撃者目的の推定結果が見つかりません。",
        "phase90_help": "実際に設定した攻撃者目的と推定された目的がどの程度一致するかを示します。",
        "phase91_behavior_profiles": "攻撃者行動の傾向分析（研究用）",
        "phase91_missing": "攻撃者行動の傾向分析結果が見つかりません。",
        "phase91_help": "攻撃者行動の傾向、推定の確からしさ、目的との関係を示します。",
        "phase92_feature_space": "評価特徴量の分析（研究用）",
        "phase92_missing": "評価特徴量の分析結果が見つかりません。",
        "phase92_help": "評価に効いている特徴と、攻撃者目的との関係を示します。",
        "phase93_profilecore": "行動プロファイルの統合分析（研究用）",
        "phase93_missing": "行動プロファイルの統合分析結果が見つかりません。",
        "phase93_help": "PCA variance、Dominant Component、Archetype Distributionを表示します。",
        "phase94_archetype": "攻撃者タイプの解釈（研究用）",
        "phase94_missing": "攻撃者タイプの解釈結果が見つかりません。",
        "phase94_help": "Archetype Summary、Signature、Feature Comparison、Mission/Profileとの関係を表示します。",
        "archetype_summary": "Archetype Summary",
        "archetype_signature": "Archetype Signature",
        "feature_comparison": "Feature Comparison",
        "mission_relationship": "Mission Relationship",
        "phase95_strategy": "攻撃戦略の分析（研究用）",
        "phase95_missing": "攻撃戦略の分析結果が見つかりません。",
        "phase95_help": "Strategy、Strategy Confidence、Mission/Archetype/Profileとの関係を表示します。",
        "strategy": "Strategy",
        "strategy_confidence": "Strategy Confidence",
        "archetype_relationship": "Archetype Relationship",
        "phase96_taxonomy": "攻撃者目的・対象の関係分析（研究用）",
        "phase96_missing": "攻撃者目的・対象の関係分析結果が見つかりません。",
        "phase96_help": "Intent → Mission → Target と Target → Strategy の関係を表示します。",
        "taxonomy_explorer": "Taxonomy Explorer",
        "target_relationship": "Target Relationship",
        "phase97_target_strategy": "対象別の攻撃戦略分析（研究用）",
        "phase97_missing": "対象別の攻撃戦略分析結果が見つかりません。",
        "phase97_help": "Target、Strategy、Target-Strategy Mapping、Alignment Scoreを表示します。",
        "target_strategy_mapping": "Target-Strategy Mapping",
        "alignment_score": "Alignment Score",
        "phase98_strategy_validation": "攻撃戦略モデルの検証（研究用）",
        "phase98_missing": "攻撃戦略モデルの検証結果が見つかりません。",
        "phase98_help": "Strategy Validation、Distinctiveness、Redundancy、Explainabilityを表示します。",
        "distinctiveness": "Distinctiveness",
        "redundancy": "Redundancy",
        "explainability": "Explainability",
        "phase99_decision_graph": "攻撃者の意思決定経路（研究用）",
        "phase99_missing": "攻撃者の意思決定経路の結果が見つかりません。",
        "phase99_help": "Decision Graph、Decision Path Explorer、Node Explorerを表示します。",
        "decision_path_explorer": "Decision Path Explorer",
        "node_explorer": "Node Explorer",
        "true_mission": "設定した攻撃者の目的",
        "inferred_mission": "推定された攻撃者の目的",
        "behavior_profile": "攻撃者行動の傾向",
        "profile_confidence": "プロファイル推定の確からしさ",
        "dominant_feature": "主な特徴",
        "critical_path_bias": "重要資産を優先する傾向",
        "accuracy": "一致率",
        "benchmark_results_missing": "横断ベンチマーク比較の結果が見つかりません。先に比較を実行してください。",
        "metric_guide": "評価指標の読み方",
        "metric_guide_text": """
        - `mission_effectiveness`: 総合評価（攻撃者の目的を防ぐ効果の高さ）
        - `mission_success_delta`: 攻撃の成功をどれだけ防げたか（低下した成功率）
        - `mission_disruption_delta`: 攻撃者の活動をどれだけ妨害できたか（増加した妨害率）
        - `mission_detection_delta`: 攻撃をどれだけ検知しやすくなったか（増加した検知率）
        - `diversion_delta`: 攻撃者にどれだけ無駄な行動や迂回を強要できたか
        - `best_mission` / `worst_mission`: この対策が最も有効な攻撃目的 / 最も効果が薄い攻撃目的
        """,
        "mission_interpretation": "目的別の読み方",
        "mission_interpretation_help": (
            "攻撃者の目的ごとに、最も評価スコアが高かった対策を抽出しています。"
            "「絶対的な最強製品」を決めるものではなく、目的によって効きやすい対策が変わることを確認するための表示です。"
        ),
        "download_csv": "CSVをダウンロード",
        "download_json": "JSONをダウンロード",
        "download_md": "Markdownをダウンロード",
        "missing": "Missing",
        "not_found": "not found.",
    },
    "English": {
        "nav": ["Home", "Scenario", "Products", "Run", "Results", "Benchmark", "Threat Hunting"],
        "nav_to_key": {
            "Home": "home",
            "Scenario": "scenario",
            "Products": "products",
            "Run": "run",
            "Results": "results",
            "Benchmark": "benchmark",
            "Threat Hunting": "hunting",
        },
        "language": "Display language",
        "report_locale": "en",
        "scope": "Product Evaluation only",
        "home_subtitle": "Product Evaluation Dashboard MVP",
        "definition": (
            "CyberMatch is a cyber decision-making simulator that reproduces attacker "
            "decision processes and enables comparative evaluation of defense strategies "
            "and security products."
        ),
        "mvp_scope": (
            "MVP scope: Product Evaluation only. The app uses existing runners and generated artifacts."
        ),
        "cert_warning": (
            "CyberMatch is not real product certification. It is a reproducible scenario "
            "evaluation framework for comparing controlled product profiles."
        ),
        "current_focus": """
        **Current MVP focus**

        - Product profile inspection
        - Mission-aware product evaluation
        - Existing artifact viewing
        - CSV, JSON, PNG, and Markdown report access
        """,
        "home_how_to": """
        **Start here (three quick steps)**

        1. Open **Run** and choose a purpose-driven demo from **Demo scenarios**.
        2. Click **Apply these demo conditions** to set missions, products, and topology.
        3. Run **Mission-Aware Product Evaluation**, then open **Results** to review the conclusion.

        CyberMatch compares which defense options should be validated first for a given attacker mission and environment.
        """,
        "scenario_title": "Scenario",
        "scenario_import": "Scenario import",
        "scenario_catalog": "Scenario catalog",
        "demo_scenarios": "Demo scenarios",
        "apply_demo": "Apply these demo conditions",
        "demo_conclusion": "Demo conclusion",
        "demo_applied": "Applied demo",
        "no_demo_scenarios": "No demo scenarios found under scenarios/demos/.",
        "scenario_name": "Scenario Name",
        "scenario_industry": "Industry",
        "scenario_description": "Description",
        "benchmark_suite": "Benchmark suite",
        "benchmark_name": "Benchmark name",
        "scenario_count": "Scenario count",
        "mission_count": "Mission count",
        "product_count": "Product count",
        "topology_count": "Topology count",
        "matrix_size": "Matrix size",
        "benchmark_json": "Benchmark JSON",
        "no_benchmarks": "No benchmark JSON files found under benchmarks/.",
        "topology_library": "Topology library",
        "topology_name": "Topology name",
        "topology_description": "Topology description",
        "topology_characteristics": "Topology characteristics",
        "topology_json": "Topology JSON",
        "no_topologies": "No topology JSON files found under topologies/.",
        "scenario_json": "Scenario JSON",
        "selected_scenario_path": "Selected scenario path",
        "no_scenarios": "No scenario JSON files found under scenarios/.",
        "scenario_selector": "Built-in scenario",
        "mission_selection": "Mission selection",
        "mission_caption": "Only selected missions are evaluated; select multiple missions to compare them.",
        "products_title": "Products",
        "no_profiles": "No product profiles found under profiles/products/.",
        "comparison_targets": "Comparison targets",
        "product_caption": "Only selected product profiles are compared.",
        "run_title": "Run",
        "run_guide": "For a demo, apply conditions from **Demo scenarios** first. For manual setup, choose topology (environment assumptions), missions (attacker objectives), and product profiles to compare. Normal GUI runs use seed `0` for fast, reproducible results.",
        "scenario_import_hook": "Scenario import hook",
        "primary_runner": "Primary runner:",
        "output": "Output:",
        "run_phase63": "Run Mission-Aware Product Evaluation",
        "run_phase83": "Run Benchmark Suite",
        "run_standard_benchmark": "Run CyberMatch Standard Benchmark",
        "stop_run": "Stop run",
        "running_phase63": "Running evaluation...",
        "runner_failed": "Runner failed",
        "runner_running": "Evaluation is running.",
        "runner_stopped": "Evaluation stopped.",
        "runner_exit_code": "Exit code",
        "runner_not_running": "No runner is currently active.",
        "phase63_done": "Evaluation completed.",
        "phase83_done": "Benchmark suite completed.",
        "phase85_done": "Standard benchmark completed.",
        "artifacts_written": "Artifacts written to",
        "optional_phase62": "Optional runner",
        "run_phase62": "Run Product Profile Evaluation",
        "running_phase62": "Running evaluation...",
        "phase62_done": "Evaluation completed.",
        "results_title": "Results",
        "decision_conclusion": "Conclusion",
        "decision_conclusion_intro": "Recommended candidates and the best fit for each selected mission.",
        "decision_reason": "Why",
        "decision_reason_intro": "For each recommended candidate, the largest change in attacker outcome is shown.",
        "decision_primary_driver": "Primary change",
        "decision_driver_success": "reduced mission success",
        "decision_driver_disruption": "increased campaign disruption",
        "decision_driver_detection": "increased detection probability",
        "decision_driver_diversion": "increased attacker diversion and wasted activity",
        "decision_comparison": "Comparison",
        "decision_comparison_intro": "Compare effectiveness differences by product and mission. Values are model evaluations under the selected conditions.",
        "decision_constraints": "Assumptions and limitations",
        "decision_constraints_text": "CyberMatch results are comparative model evaluations under the recorded inputs and assumptions. They do not certify products or prove real-world effectiveness.",
        "advanced_analysis": "Detailed analysis",
        "run_conditions": "Run conditions",
        "run_manifest": "Run manifest",
        "select_topology_error": "Select a topology before running the evaluation.",
        "select_mission_error": "Select at least one mission before running the evaluation.",
        "select_product_error": "Select at least one product profile before running the evaluation.",
        "results_missing": "Results not found. Run the evaluation first.",
        "go_to_run": "Open the Run page and execute the evaluation.",
        "expected_output_path": "Expected output path",
        "missing_files": "Missing files",
        "results_intro": (
            "This page displays generated artifacts. Chart labels come from "
            "the existing runner output; use the explanations below to interpret each view."
        ),
        "interpretation_notice": (
            "CyberMatch does not certify one universally strongest product. It is an "
            "evaluation dashboard for comparing effectiveness differences by attacker mission."
        ),
        "summary_cards": "Summary cards",
        "best_product_overall": "Best product overall",
        "best_product_per_mission": "Best product per mission",
        "worst_mission_coverage": "Worst mission coverage",
        "highest_mission_variance": "Highest mission variance",
        "single_winner_exists": "Single winner exists",
        "product_mission_table": "Product x Mission table",
        "product_mission_chart": "Product x Mission table heatmap",
        "winner_explanation": "Mission winner explanation",
        "product_detail": "Product detail",
        "product_selector": "Product profile",
        "detail_metric": "Metric",
        "detail_value": "Value",
        "per_mission_detail": "Per-mission detail",
        "summary_table": "Summary table",
        "heatmap": "Product x Mission heatmap",
        "heatmap_help": (
            "The heatmap shows mission_effectiveness for each product profile and attacker mission. "
            "Rows are products/profiles, columns are missions, and stronger color means stronger "
            "mission-specific effectiveness."
        ),
        "variance": "Mission variance",
        "variance_help": (
            "Mission variance shows how differently the same product profile performs across missions. "
            "A larger value means the effect is more mission-dependent."
        ),
        "phase62_comparison": "Base vs Mission-Aware Comparison",
        "phase62_help": (
            "This view contrasts profile-level evaluation with mission-aware evaluation. "
            "It should be read as mission suitability, not a single ranking."
        ),
        "markdown_report": "Markdown report",
        "json_summary": "JSON summary",
        "downloads": "Downloads",
        "benchmark_artifacts": "Benchmark artifacts",
        "phase90_intent_inference": "Intent Inference",
        "phase90_missing": "Intent inference artifacts not found.",
        "phase90_help": "Displays True Mission, Inferred Mission, Confidence, Accuracy, and Confusion Matrix.",
        "phase91_behavior_profiles": "Behavior Profiles",
        "phase91_missing": "Behavior profile artifacts not found.",
        "phase91_help": "Displays Behavior Profile, Profile Confidence, Profile Distribution, and Mission Relationship.",
        "phase92_feature_space": "Feature Space",
        "phase92_missing": "Feature space artifacts not found.",
        "phase92_help": "Displays Dominant Feature, Critical Path Bias, Feature Dominance, and Mission Feature Heatmap.",
        "phase93_profilecore": "ProfileCore",
        "phase93_missing": "ProfileCore artifacts not found.",
        "phase93_help": "Displays PCA variance, Dominant Component, and Archetype Distribution.",
        "phase94_archetype": "Archetype Interpretation",
        "phase94_missing": "Archetype interpretation artifacts not found.",
        "phase94_help": "Displays Archetype Summary, Signature, Feature Comparison, and Mission/Profile relationships.",
        "archetype_summary": "Archetype Summary",
        "archetype_signature": "Archetype Signature",
        "feature_comparison": "Feature Comparison",
        "mission_relationship": "Mission Relationship",
        "phase95_strategy": "Strategy Layer",
        "phase95_missing": "Strategy layer artifacts not found.",
        "phase95_help": "Displays Strategy, Strategy Confidence, and Mission/Archetype/Profile relationships.",
        "strategy": "Strategy",
        "strategy_confidence": "Strategy Confidence",
        "archetype_relationship": "Archetype Relationship",
        "phase96_taxonomy": "Taxonomy Explorer",
        "phase96_missing": "Taxonomy artifacts not found.",
        "phase96_help": "Displays Intent -> Mission -> Target and Target -> Strategy relationships.",
        "taxonomy_explorer": "Taxonomy Explorer",
        "target_relationship": "Target Relationship",
        "phase97_target_strategy": "Target-Specific Strategy",
        "phase97_missing": "Target strategy artifacts not found.",
        "phase97_help": "Displays Target, Strategy, Target-Strategy Mapping, and Alignment Score.",
        "target_strategy_mapping": "Target-Strategy Mapping",
        "alignment_score": "Alignment Score",
        "phase98_strategy_validation": "Strategy Validation",
        "phase98_missing": "Strategy validation artifacts not found.",
        "phase98_help": "Displays Strategy Validation, Distinctiveness, Redundancy, and Explainability.",
        "distinctiveness": "Distinctiveness",
        "redundancy": "Redundancy",
        "explainability": "Explainability",
        "phase99_decision_graph": "Decision Graph",
        "phase99_missing": "Decision graph artifacts not found.",
        "phase99_help": "Displays the Decision Graph, Decision Path Explorer, and Node Explorer.",
        "decision_path_explorer": "Decision Path Explorer",
        "node_explorer": "Node Explorer",
        "true_mission": "True Mission",
        "inferred_mission": "Inferred Mission",
        "behavior_profile": "Behavior Profile",
        "profile_confidence": "Profile Confidence",
        "dominant_feature": "Dominant Feature",
        "critical_path_bias": "Critical Path Bias",
        "accuracy": "Accuracy",
        "benchmark_results_missing": "Benchmark results not found. Run the benchmark suite first.",
        "metric_guide": "Metric guide",
        "metric_guide_text": """
        - `mission_effectiveness`: product profile effect for a specific mission.
        - `mission_success_delta`: reduction in mission success compared with baseline.
        - `mission_disruption_delta`: increase in campaign disruption.
        - `mission_detection_delta`: increase in detection probability.
        - `diversion_delta`: increase in attacker diversion.
        - `best_mission` / `worst_mission`: mission where a profile is strongest / weakest.
        """,
        "mission_interpretation": "Mission interpretation",
        "mission_interpretation_help": (
            "This table extracts the profile with the highest mission_effectiveness for each mission "
            "from the summary CSV. It is a reading aid, not product certification or a universal ranking."
        ),
        "download_csv": "Download CSV",
        "download_json": "Download JSON",
        "download_md": "Download Markdown",
        "missing": "Missing",
        "not_found": "not found.",
    },
}
